// Package nasm provides NASM assembler file writer implementation for x86 DOS .com files.
package nasm

import (
	"fmt"
	"io"
	"strings"

	"github.com/retroenv/retrodisasm/internal/assembler"
	"github.com/retroenv/retrodisasm/internal/options"
	"github.com/retroenv/retrodisasm/internal/program"
	"github.com/retroenv/retrodisasm/internal/writer"
)

// FileWriter writes NASM assembly files.
type FileWriter struct {
	app           *program.Program
	options       options.Disassembler
	mainWriter    io.Writer
	newBankWriter assembler.NewBankWriter
	writer        *writer.Writer
}

// New creates a new NASM file writer.
func New(app *program.Program, options options.Disassembler, mainWriter io.Writer, newBankWriter assembler.NewBankWriter) writer.AssemblerWriter {
	opts := writer.Options{
		OffsetComments: options.OffsetComments,
	}
	return &FileWriter{
		app:           app,
		options:       options,
		mainWriter:    mainWriter,
		newBankWriter: newBankWriter,
		writer:        writer.New(app, mainWriter, opts),
	}
}

// Write writes the NASM assembly file.
func (w *FileWriter) Write() error {
	// Write NASM header comments
	if _, err := fmt.Fprintf(w.mainWriter, "; DOS .com file disassembly\n"); err != nil {
		return fmt.Errorf("writing header comment: %w", err)
	}

	if _, err := fmt.Fprintf(w.mainWriter, "; Generated by retrodisasm\n\n"); err != nil {
		return fmt.Errorf("writing generator comment: %w", err)
	}

	// Write NASM directives
	if _, err := fmt.Fprintf(w.mainWriter, "bits 16\n"); err != nil {
		return fmt.Errorf("writing bits directive: %w", err)
	}

	baseAddr := w.app.CodeBaseAddress
	if baseAddr == 0 {
		baseAddr = 0x0100 // Default for DOS .com files
	}

	if _, err := fmt.Fprintf(w.mainWriter, "org 0x%04X\n\n", baseAddr); err != nil {
		return fmt.Errorf("writing org directive: %w", err)
	}

	// Write program banks
	for _, bank := range w.app.PRG {
		if err := w.writeBank(bank); err != nil {
			return fmt.Errorf("writing bank: %w", err)
		}
	}

	return nil
}

// writeBank writes a program bank.
func (w *FileWriter) writeBank(bank *program.PRGBank) error {
	endIndex := w.getEndIndex(bank)

	for i := range endIndex {
		offset := bank.Offsets[i]

		if len(offset.Data) == 0 && offset.Code == "" {
			continue
		}

		if err := w.writeLabel(offset); err != nil {
			return fmt.Errorf("writing label: %w", err)
		}

		if err := w.writeOffset(offset); err != nil {
			return fmt.Errorf("writing offset: %w", err)
		}
	}

	return nil
}

// writeLabel writes a label if present in the offset.
func (w *FileWriter) writeLabel(offset program.Offset) error {
	if offset.Label != "" {
		if _, err := fmt.Fprintf(w.mainWriter, "%s:\n", offset.Label); err != nil {
			return fmt.Errorf("writing label %s: %w", offset.Label, err)
		}
	}
	return nil
}

// writeOffset writes either code or data for an offset.
func (w *FileWriter) writeOffset(offset program.Offset) error {
	if offset.Code != "" {
		return w.writeCode(offset)
	}
	if len(offset.Data) > 0 {
		return w.writeData(offset)
	}
	return nil
}

// writeCode writes an instruction.
func (w *FileWriter) writeCode(offset program.Offset) error {
	line := "    " + offset.Code

	if offset.Comment == "" {
		if _, err := fmt.Fprintf(w.mainWriter, "%s\n", line); err != nil {
			return fmt.Errorf("writing code: %w", err)
		}
	} else {
		if _, err := fmt.Fprintf(w.mainWriter, "%-40s ; %s\n", line, offset.Comment); err != nil {
			return fmt.Errorf("writing code with comment: %w", err)
		}
	}

	return nil
}

// writeData writes raw data bytes using NASM db directive.
func (w *FileWriter) writeData(offset program.Offset) error {
	var buf strings.Builder
	buf.WriteString(fmt.Sprintf("    db 0x%02X", offset.Data[0]))

	for j := 1; j < len(offset.Data); j++ {
		buf.WriteString(fmt.Sprintf(", 0x%02X", offset.Data[j]))
	}

	line := buf.String()

	if offset.Comment == "" {
		if _, err := fmt.Fprintf(w.mainWriter, "%s\n", line); err != nil {
			return fmt.Errorf("writing data: %w", err)
		}
	} else {
		if _, err := fmt.Fprintf(w.mainWriter, "%-40s ; %s\n", line, offset.Comment); err != nil {
			return fmt.Errorf("writing data with comment: %w", err)
		}
	}

	return nil
}

// getEndIndex finds the last meaningful byte in the program.
func (w *FileWriter) getEndIndex(bank *program.PRGBank) int {
	if w.options.ZeroBytes {
		return len(bank.Offsets)
	}

	for i := len(bank.Offsets) - 1; i >= 0; i-- {
		offset := bank.Offsets[i]
		if len(offset.Data) > 0 {
			for _, b := range offset.Data {
				if b != 0 {
					return i + 1
				}
			}
		}
		if offset.Label != "" || offset.Code != "" {
			return i + 1
		}
	}

	return 0
}
