name: CI

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  build:
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft || !contains(github.event.commits[0].message, '[skip ci]') }}
    timeout-minutes: 15

    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ "1.22.x", "stable" ]

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.go }}

      - name: Install linters
        if: matrix.go == 'stable'
        run: make install-linters

      - name: Install ca65
        run: sudo apt-get install -y cc65

      - name: Get dependencies
        run: go version && go mod download

      - name: Run tests
        run: make test

      - name: Run linter
        if: matrix.go == 'stable'
        run: make lint
